Display: {Color Display Pixel Size: 8, Color Display X Offset: 20, Color Display Y Offset: 100,
  Left side score justify: right, RGB DMD Brightness: 70}
Gameplay (Feature): {A2.01 Timed Plunger: 0, Adventure Challenge Timer: 20, Adventure Continue Timer: 25,
  Attract Mode Music: 'Yes', Attract Mode Sounds: 'Yes', Ball Saver Timer: 12, Buy Extra Ball - Buy-In Feature: 'No',
  Buy-In Ball Saver Timer: 15, Captive Multiball Start: 3, Captive Multiball Start Timer: 30,
  Castle Brunwald Timer: 35, Chain feature difficulty: medium, Choose Wisely Choice Timer: 20,
  Choose Wisely Level Start: 1, Coin Door Ball Save: 'Yes', Crimescene levels for finale: 16,
  Crimescene shot difficulty: medium, Disable Ark Mech: 'No', Dog Fight Timer: 30,
  Flipper Plunger: 'No', Frankenstein Timer: 60, Game Ballsaves: 3, Game ballsaves: 3,
  Get The Idol Awards Locks: 'Yes', Get The Idol Difficulty: Medium, Get The Idol Timer: 30,
  Gun Trigger During Buy-In: Extra Ball, Hand Of Fate Lit Difficulty: Easy, Hand Of Fate Timer: 0,
  Hold Idol Locks At Game Over: 'No', Jackport Multiplier Timer: 30, Jackpot Multiplier Timer: 30,
  Jones Target Banks For 8 Ball: 3, Jones Vs Aliens Timer: 90, Loop Lit Timer: 15,
  Loopin Jackpots Start: 20, Loopin Jackpots Timer: 35, Lower Playfield Extra Ball Lit Hold: 'On',
  Max Balls in Ark: 6, Max extra balls lit: 99, Max extra balls per game: 99, Mine Cart Tunnel Inc.: 10,
  Mine Cart Tunnel Start: 25, Mode Bonus Value (Mil): 2, Mode Start Lit: Ball Start,
  Mode Start Value (Mil): 3, Mode Timers Pause Length: 2.0, Monkey Brains Timer: 30,
  Monster Extras: 'Yes', Moonlight Mins to Midnight: 15, Multiball Ballsaves: 2, Multiball Saver Timer: 5,
  Multiball ballsave time: 20, Multiball ballsaves: 2, New ball ballsave time: 10,
  New ball repeating ballsave: false, Nuke Test Timer: 30, Outlane Ball Save: 'Yes',
  Path Of Adventure Start Level: 1, Path of Adventure Extra Ball/Pit Lit Difficulty: Easy,
  Path of Adventure Pit Lit Level: 3, Plane Chase Memory: 'Yes', Quick Multiball Saver Timer: 5,
  Ramp Lit Timer: 30, Raven Bar Animate Scores For Hits: 'Yes', Raven Bar Hits For Extra Ball: 15,
  Raven Bar Hits For Medallion: 20, Raven Bar Level Start: 1, Raven Bar Level Started: 1,
  Raven Bar Lives: 5, Return The Skull Timer: 30, Ringmaster Extras: 'Yes', Ringmaster Timer: 60.0,
  Rope Bridge Timer: 30, Steal The Stones Timer: 30, Streets Of Cairo Timer: 30, Super Jets Boost: 25,
  Super Jets Start: 10, Tank Chase Timer: 30, Temple Hits For Lock: 3, The 3 Challenges Timer: 30,
  Time per chain feature: 30, Timed Plunger: 0, Totem Hidden Music: 'Yes', Warehouse Hold Timer: 20,
  Warehouse Raid BIP Start: 2, Warehouse Raid Ball Save Timer: 10, Well Of Souls BIP Start: 4,
  Well Of Souls Ball Save Timer: 12}
Highscore: {Grand Champion: 350000000}
Machine (Standard): {Allow Dim Illumination: 'No', Ball Search Timer: 15, Balls Per Game: 4,
  Clock Style: AM/PM, Custom Message: false, Date Style: Euro, Euro. Score Format: 'No',
  Free Play: 'Yes', Game Restart: true, General Illumination Power Saver: 0, Maximum Extra Balls: 4,
  Maximum Extra Balls/Ball In Play: 0, No Bonus Flips: 'Yes', Party Mode: 'Off', Power Saver Level: 4,
  Shaker Installed: 'No', Show Date and Time: 'Yes', Tilt Warnings: 3, Tournament Play: 'No',
  Tournament Type: Local}
Network: {Display Server Scores in Attract: 'No', Gateway: 0, IP Address: 0, Store High Scores on Server: 'No',
  Subnet: 0, Tournament Server: 0}
Replay: {Replay Award: Audit, Replay Boost: 100000, Replay Level 1: 100000, Replay Level 2: 200000,
  Replay Level 3: 300000, Replay Level 4: 400000, Replay Levels: 1, Replay Percentage: 10,
  Replay Type: auto, Special: Audit}
Sound: {Extended Speech: 'Yes', Initial Volume: 26}
